apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaizen.fullname" . }}-portal
  labels:
    app.kubernetes.io/name: portal
    app.kubernetes.io/part-of: kaizen
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: portal
  ports:
    - name: http
      port: 8080
      targetPort: {{ .Values.portal.port }}
