from typing import Protocol, Any


class IBrowser(Protocol):
    """Thin browser fa?ade (Playwright adapter will implement this)."""

    async def open(self, url: str) -> None: ...
    async def click(self, locator: Any) -> None: ...
    async def type(self, locator: Any, text: str, clear: bool = False) -> None: ...
    async def press(self, key: str) -> None: ...
    async def screenshot(self, path: str) -> None: ...
    async def frames(self) -> list[Any]: ...
    async def evaluate(self, script: str) -> Any: ...
    async def scroll(self, x: int, y: int) -> None: ...
    # Extended core actions (optional for simple fakes)
    async def dblclick(self, locator: Any) -> None: ...
    async def right_click(self, locator: Any) -> None: ...
    async def hover(self, locator: Any) -> None: ...
    async def focus(self, locator: Any) -> None: ...
    async def blur(self, locator: Any) -> None: ...
    async def clear(self, locator: Any) -> None: ...
    async def select_option(self, locator: Any, option: dict) -> None: ...
    async def set_input_files(self, locator: Any, files: list[str]) -> None: ...
    async def drag(self, locator: Any, dx: int, dy: int) -> None: ...
    async def drag_and_drop(self, source: Any, target: Any) -> None: ...
    # Navigation primitives
    async def reload(self) -> None: ...
    async def go_back(self) -> None: ...
    async def go_forward(self) -> None: ...
    async def new_tab(self, url: str | None = None) -> None: ...
    async def new_window(self, url: str | None = None) -> None: ...
    async def switch_tab(self, index: int | None = None, url_contains: str | None = None, title_contains: str | None = None) -> None: ...
    async def switch_window(self, index: int | None = None, url_contains: str | None = None, title_contains: str | None = None) -> None: ...
    async def close_tab(self, index: int | None = None) -> None: ...
    async def close_window(self, index: int | None = None) -> None: ...


class ISnapshotter(Protocol):
    """Capture PageSnapshot → DOM/candidates/styles/screenshot/frames."""

    async def snapshot(self) -> "PageSnapshot": ...
