from typing import Protocol, Any


class IBrowser(Protocol):
    """Thin browser façade (Playwright adapter will implement this)."""

    async def open(self, url: str) -> None: ...
    async def click(self, locator: Any) -> None: ...
    async def type(self, locator: Any, text: str, clear: bool = False) -> None: ...
    async def press(self, key: str) -> None: ...
    async def screenshot(self, path: str) -> None: ...
    async def frames(self) -> list[Any]: ...
    async def evaluate(self, script: str) -> Any: ...
    async def scroll(self, x: int, y: int) -> None: ...


class ISnapshotter(Protocol):
    """Capture PageSnapshot → DOM/candidates/styles/screenshot/frames."""

    async def snapshot(self) -> "PageSnapshot": ...
